// Data Model: collectionModel
module.exports = {
  id: "collectionModel",
  label: "Collection",
  description:
    "Defines a seasonal or thematic collection and the related launch metadata.",
  isEditable: true,
  attributes: [
    {
      id: "id",
      type: "string",
      label: "ID",
      required: true,
      unique: true,
      indexed: true,
    },
    {
      id: "description",
      type: "string",
      label: "Description",
      defaultValue: "",
    },
    {
      id: "startDate",
      type: "date",
      label: "Start Date",
      required: true,
    },
    {
      id: "endDate",
      type: "date",
      label: "End Date",
    },
    {
      id: "createdBy",
      type: "string",
      label: "Created By",
      accessControl: {
        read: ["admin"],
        write: ["admin"],
      },
    },
    {
      id: "createdAt",
      type: "datetime",
      label: "Created At",
    },
    {
      id: "status",
      type: "string",
      label: "Status",
      defaultValue: "draft",
      allowedValues: ["draft", "active", "inactive", "archived"],
    },
    {
      id: "version",
      type: "number",
      label: "Version",
      defaultValue: 1,
    },
    {
      id: "createdAge",
      type: "computed",
      label: "Age (days)",
      dependencies: ["createdAt"],
    },
    {
      id: "collection_title",
      label: "Title",
      type: "text",
      description: "Collection title shown in marketing and store.",
      required: false,
      unique: false,
      indexed: false,
      controlType: "text",
    },
    {
      id: "collection_code",
      label: "Collection code",
      type: "text",
      description: "Internal code used to link products to the collection.",
      required: false,
      unique: false,
      indexed: false,
      controlType: "text",
    },
    {
      id: "collection_description",
      label: "Description",
      type: "text",
      description:
        "Narrative or concept behind the collection (aesthetic, cultural notes).",
      required: false,
      unique: false,
      indexed: false,
      controlType: "text",
    },
    {
      id: "collection_launchDate",
      label: "Launch date",
      type: "date",
      description: "Scheduled public launch date for the collection.",
      required: false,
      unique: false,
      indexed: false,
      controlType: "text",
    },
    {
      id: "collection_season",
      label: "Season",
      type: "text",
      description: "Season or year tag (e.g., Spring 2026).",
      required: false,
      unique: false,
      indexed: false,
      controlType: "text",
    },
    {
      id: "collection_theme",
      label: "Theme",
      type: "text",
      description: "Short theme or mood board reference.",
      required: false,
      unique: false,
      indexed: false,
      controlType: "text",
    },
    {
      id: "collection_featuredProductSKUs",
      label: "Featured product SKUs",
      type: "text",
      description:
        "Comma-separated SKUs of highlighted products for this collection.",
      required: false,
      unique: false,
      indexed: false,
      controlType: "text",
    },
  ],
  extends: null,
  isProtected: false,
};
