// Data Model: customerModel
module.exports = {
  id: "customerModel",
  label: "Customer",
  description:
    "Customer identity and preferences used across orders and post-purchase experiences.",
  isEditable: true,
  attributes: [
    {
      id: "id",
      type: "string",
      label: "ID",
      required: true,
      unique: true,
      indexed: true,
    },
    {
      id: "description",
      type: "string",
      label: "Description",
      defaultValue: "",
    },
    {
      id: "startDate",
      type: "date",
      label: "Start Date",
      required: true,
    },
    {
      id: "endDate",
      type: "date",
      label: "End Date",
    },
    {
      id: "createdBy",
      type: "string",
      label: "Created By",
      accessControl: {
        read: ["admin"],
        write: ["admin"],
      },
    },
    {
      id: "createdAt",
      type: "datetime",
      label: "Created At",
    },
    {
      id: "status",
      type: "string",
      label: "Status",
      defaultValue: "draft",
      allowedValues: ["draft", "active", "inactive", "archived"],
    },
    {
      id: "version",
      type: "number",
      label: "Version",
      defaultValue: 1,
    },
    {
      id: "createdAge",
      type: "computed",
      label: "Age (days)",
      dependencies: ["createdAt"],
    },
    {
      id: "customer_firstName",
      label: "First name",
      type: "text",
      description: "Customer first name.",
      required: false,
      unique: false,
      indexed: false,
      controlType: "text",
    },
    {
      id: "customer_lastName",
      label: "Last name",
      type: "text",
      description: "Customer last name.",
      required: false,
      unique: false,
      indexed: false,
      controlType: "text",
    },
    {
      id: "customer_email",
      label: "Email",
      type: "email",
      description:
        "Primary contact email for order and marketing communications.",
      required: false,
      unique: false,
      indexed: false,
      controlType: "text",
    },
    {
      id: "customer_phone",
      label: "Phone",
      type: "text",
      description: "Contact phone number.",
      required: false,
      unique: false,
      indexed: false,
      controlType: "text",
    },
    {
      id: "customer_address",
      label: "Address",
      type: "text",
      description: "Default shipping address for the customer.",
      required: false,
      unique: false,
      indexed: false,
      controlType: "text",
    },
    {
      id: "customer_preferences",
      label: "Style preferences",
      type: "text",
      description:
        "Optional notes on modesty, sizing preferences, or fabric preferences.",
      required: false,
      unique: false,
      indexed: false,
      controlType: "text",
    },
  ],
  extends: null,
  isProtected: false,
};
