// Data Model: orderModel
module.exports = {
  id: "orderModel",
  label: "Order",
  description: "Captures purchase transaction details and fulfillment status.",
  isEditable: true,
  attributes: [
    {
      id: "id",
      type: "string",
      label: "ID",
      required: true,
      unique: true,
      indexed: true,
    },
    {
      id: "description",
      type: "string",
      label: "Description",
      defaultValue: "",
    },
    {
      id: "startDate",
      type: "date",
      label: "Start Date",
      required: true,
    },
    {
      id: "endDate",
      type: "date",
      label: "End Date",
    },
    {
      id: "createdBy",
      type: "string",
      label: "Created By",
      accessControl: {
        read: ["admin"],
        write: ["admin"],
      },
    },
    {
      id: "createdAt",
      type: "datetime",
      label: "Created At",
    },
    {
      id: "status",
      type: "string",
      label: "Status",
      defaultValue: "draft",
      allowedValues: ["draft", "active", "inactive", "archived"],
    },
    {
      id: "version",
      type: "number",
      label: "Version",
      defaultValue: 1,
    },
    {
      id: "createdAge",
      type: "computed",
      label: "Age (days)",
      dependencies: ["createdAt"],
    },
    {
      id: "order_orderId",
      label: "Order ID",
      type: "text",
      description: "Unique order identifier.",
      required: false,
      unique: false,
      indexed: false,
      controlType: "text",
    },
    {
      id: "order_customerEmail",
      label: "Customer email",
      type: "email",
      description: "Customer email used for this order.",
      required: false,
      unique: false,
      indexed: false,
      controlType: "text",
    },
    {
      id: "order_date",
      label: "Order date",
      type: "date",
      description: "Date the order was placed.",
      required: false,
      unique: false,
      indexed: false,
      controlType: "text",
    },
    {
      id: "order_items",
      label: "Items",
      type: "text",
      description: "Line items in the order (SKU x qty).",
      required: false,
      unique: false,
      indexed: false,
      controlType: "text",
    },
    {
      id: "order_totalAmount",
      label: "Total amount",
      type: "number",
      description: "Total payable amount for the order.",
      required: false,
      unique: false,
      indexed: false,
      controlType: "text",
    },
    {
      id: "order_paymentStatus",
      label: "Payment status",
      type: "text",
      description: "Payment state (e.g., Paid, Pending, Failed).",
      required: false,
      unique: false,
      indexed: false,
      controlType: "text",
    },
    {
      id: "order_shippingAddress",
      label: "Shipping address",
      type: "text",
      description: "Fulfillment/shipping address for the order.",
      required: false,
      unique: false,
      indexed: false,
      controlType: "text",
    },
    {
      id: "order_trackingNumber",
      label: "Tracking number",
      type: "text",
      description: "Carrier tracking number once shipment is dispatched.",
      required: false,
      unique: false,
      indexed: false,
      controlType: "text",
    },
  ],
  extends: null,
  isProtected: false,
};
